create table RawQualityInspection(
Inspection_ID varchar,
Inspection_Date varchar,
Inspection_Time varchar,
Year int,
Month int,
Order_ID varchar,
Product_ID varchar,
Product_Name varchar,
Batch_Number varchar,
Inspector_ID varchar,
Inspector_Name varchar,
InspectorDepartment varchar,
Department varchar,
Factory_ID varchar,
Factory_Name varchar,
Assembly_Line_ID varchar,
Assembly_Line_Name varchar,
Quantity_Inspected int,
Quantity_Defective int,
Defect_Rate float,
Sample_Size int,
Defect_Type varchar,
Defect_Code varchar,
Defect_Severity varchar,
Defect_Description varchar,
Dimension1 float,
Dimension2 float,
Weight float,
Visual_Quality varchar,
Functional_Test varchar,
Inspection_Status varchar,
Inspection_Result varchar,
Rework_Required varchar,
Approved varchar,
ApprovedBy varchar,
Notes varchar,
PhotoPath varchar
)
select * from RawQualityInspection

insert into RawQualityInspection values(
'INSP00000001','2024-06-23','08:53',2024,8,'ORD00000569','PROD000002','Product 2',
'BATCH00001','INS0002','Inspector 2','Quality Control','QC Department','FAC02',
'Factory 2','LINE002','Assembly Line 2',4249,63,1.48,3943,'Dent','D002',
'Major','Dent found in batch',28.47,69.94,14.89,'Good','Pass','In Progress',
'Failed','Yes','No',null,'Inspection completed - 1.48% defect rate',
'photo_INSP00000001.jpg'
)